name: Daily Run

on:
  schedule:
    - cron: '40 13 * * *'  # Runs every day at 8:40 AM EST (13:40 UTC)
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Update system dependencies
      run: sudo apt-get update

   # - name: Download Gecko webdriver, unzip archive, add to path
   #   run: curl -o ${GITHUB_WORKSPACE}/gecko.tar.gz -L https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz && tar -xvf gecko.tar.gz && export PATH=$PATH:${GITHUB_WORKSPACE}/
    
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    
    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb


#    - name: Remove default Chromium
#      run: sudo apt purge chromium-browser

#    - name: Install a new Chromium
#      run: sudo apt install -y chromium-browser

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install all (OTHER?) necessary packages
      run: pip install requests beautifulsoup4 pandas selenium chromedriver-autoinstaller pyvirtualdisplay
  
    - name: Run script
      run: python runall.py

    - name: Configure git
      run: |
        git config --global user.email "actions-user@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit changes
      env:
        TZ: America/New_York
      run: |
        CURRENT_DATE=$(date +"%m/%d/%Y")
        git add .
        git commit -m "run ($CURRENT_DATE)" -a || echo "No changes to commit"
        git push
