name: Daily Run

on:
  schedule:
    - cron: '15 21 * * *'  # Runs every day at 4:15 PM EST (21:15 UTC)

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python runall.py
