name: Daily Run

on:
  schedule:
    - cron: '40 13 * * *'  # Runs every day at 8:40 AM EST (13:40 UTC)
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python runall.py

    - name: Configure git
      run: |
        git config --global user.email "actions-user@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit changes
      env:
        TZ: America/New_York
      run: |
        CURRENT_DATE=$(date +"%m/%d/%Y")
        git add .
        git commit -m "run ($CURRENT_DATE)" -a || echo "No changes to commit"
        git push
